services:
    web:
        build: .
        container_name: meadowlark-dev
        volumes:
            - .:/usr/src/app
        ports:
            - "3000:3000"
            - "3001:3001"
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=1
        stdin_open: true
        tty: true
